-- prodify-layer/db/schema.sql
-- Generated by Prodify — Supabase SQL migration
-- Run in your Supabase project: Dashboard → SQL Editor, or via: supabase db push

-- ── Helper: auto-update updated_at on any table ────────────────────────────
CREATE OR REPLACE FUNCTION public.set_updated_at()
RETURNS TRIGGER LANGUAGE plpgsql AS $$
BEGIN
  NEW.updated_at = now();
  RETURN NEW;
END;
$$;

-- ── Users (mirror of auth.users with billing fields) ───────────────────────
-- subscription_tier is enforced by CHECK — invalid values fail at DB level, not silently.
CREATE TABLE IF NOT EXISTS public.users (
  id                     UUID PRIMARY KEY REFERENCES auth.users(id) ON DELETE CASCADE,
  email                  TEXT UNIQUE NOT NULL,
  full_name              TEXT,
  avatar_url             TEXT,
  stripe_customer_id     TEXT UNIQUE,
  subscription_tier      TEXT NOT NULL DEFAULT 'free'
                           CHECK (subscription_tier IN ('free', 'pro', 'enterprise')),
  subscription_status    TEXT NOT NULL DEFAULT 'inactive'
                           CHECK (subscription_status IN (
                             'active', 'inactive', 'past_due',
                             'canceled', 'trialing', 'paused', 'unpaid'
                           )),
  current_period_end     TIMESTAMPTZ,
  created_at             TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at             TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS users_stripe_customer_id_idx ON public.users (stripe_customer_id);

ALTER TABLE public.users ENABLE ROW LEVEL SECURITY;
CREATE POLICY "users: own row" ON public.users
  FOR ALL USING (auth.uid() = id);

DROP TRIGGER IF EXISTS users_set_updated_at ON public.users;
CREATE TRIGGER users_set_updated_at
  BEFORE UPDATE ON public.users
  FOR EACH ROW EXECUTE FUNCTION public.set_updated_at();

-- ── Subscriptions (Stripe lifecycle per user) ───────────────────────────────
CREATE TABLE IF NOT EXISTS public.subscriptions (
  id                     UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  user_id                UUID NOT NULL REFERENCES public.users(id) ON DELETE CASCADE,
  stripe_subscription_id TEXT UNIQUE,
  stripe_price_id        TEXT,
  status                 TEXT NOT NULL DEFAULT 'inactive'
                           CHECK (status IN (
                             'active', 'inactive', 'past_due',
                             'canceled', 'trialing', 'paused', 'unpaid'
                           )),
  current_period_start   TIMESTAMPTZ,
  current_period_end     TIMESTAMPTZ,
  cancel_at              TIMESTAMPTZ,
  canceled_at            TIMESTAMPTZ,
  created_at             TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at             TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS subscriptions_user_id_idx ON public.subscriptions (user_id);
CREATE INDEX IF NOT EXISTS subscriptions_stripe_sub_id_idx ON public.subscriptions (stripe_subscription_id);

ALTER TABLE public.subscriptions ENABLE ROW LEVEL SECURITY;
CREATE POLICY "subscriptions: own rows" ON public.subscriptions
  FOR ALL USING (auth.uid() = user_id);

DROP TRIGGER IF EXISTS subscriptions_set_updated_at ON public.subscriptions;
CREATE TRIGGER subscriptions_set_updated_at
  BEFORE UPDATE ON public.subscriptions
  FOR EACH ROW EXECUTE FUNCTION public.set_updated_at();

-- ── Webhook events (idempotency store for Stripe events) ────────────────────
-- No public SELECT policy — only accessible via service-role key in webhook handler.
CREATE TABLE IF NOT EXISTS public.webhook_events (
  id              UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  stripe_event_id TEXT UNIQUE NOT NULL,
  type            TEXT NOT NULL,
  payload         JSONB NOT NULL,
  processed_at    TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS webhook_events_type_idx ON public.webhook_events (type);

ALTER TABLE public.webhook_events ENABLE ROW LEVEL SECURITY;
-- Intentionally no public policy: only service-role can write/read webhook_events.

-- ── Auto-create users row on first sign-in ──────────────────────────────────
CREATE OR REPLACE FUNCTION public.handle_new_user()
RETURNS TRIGGER LANGUAGE plpgsql SECURITY DEFINER SET search_path = public AS $$
BEGIN
  INSERT INTO public.users (id, email, full_name, avatar_url)
  VALUES (
    NEW.id,
    NEW.email,
    NEW.raw_user_meta_data->>'full_name',
    NEW.raw_user_meta_data->>'avatar_url'
  )
  ON CONFLICT (id) DO NOTHING;
  RETURN NEW;
END;
$$;

DROP TRIGGER IF EXISTS on_auth_user_created ON auth.users;
CREATE TRIGGER on_auth_user_created
  AFTER INSERT ON auth.users
  FOR EACH ROW EXECUTE FUNCTION public.handle_new_user();
