// prodify-layer/supabase/server.ts
// Generated by Prodify — Supabase server client (App Router / Route Handlers)
// Uses @supabase/ssr which handles cookie-based sessions correctly in Next.js 13+
import { createServerClient } from '@supabase/ssr';
import { createClient } from '@supabase/supabase-js';
import { cookies } from 'next/headers';

export async function createSupabaseServerClient() {
  const cookieStore = await cookies();
  return createServerClient(
    process.env.NEXT_PUBLIC_SUPABASE_URL!,
    process.env.NEXT_PUBLIC_SUPABASE_ANON_KEY!,
    {
      cookies: {
        getAll: () => cookieStore.getAll(),
        setAll: (cookiesToSet) => {
          try {
            cookiesToSet.forEach(({ name, value, options }) =>
              cookieStore.set(name, value, options),
            );
          } catch {
            // setAll called from a Server Component — cookies are read-only.
            // Middleware handles the actual refresh, so this is safe to ignore.
          }
        },
      },
    },
  );
}

/**
 * Service-role client — bypasses RLS.
 * ONLY use in trusted server contexts: webhook handlers, admin routes.
 * NEVER expose SUPABASE_SERVICE_ROLE_KEY to the client or prefix it NEXT_PUBLIC_.
 */
export function createSupabaseServiceClient() {
  return createClient(
    process.env.NEXT_PUBLIC_SUPABASE_URL!,
    process.env.SUPABASE_SERVICE_ROLE_KEY!,
    { auth: { autoRefreshToken: false, persistSession: false } },
  );
}
